{% set name = "flask-mqtt" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stlehmann/Flask-MQTT/releases/download/{{ version }}/Flask-MQTT-{{ version }}.tar.gz
  sha256: 6d37c5ebb8e180f6aaa409d776a04f6dcf2fcd61cc22d67341bc146db36641e0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - flask
    - paho-mqtt

test:
  imports:
    - flask_mqtt

about:
  home: https://github.com/stlehmann/Flask-MQTT
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple, Flask Extension for the MQTT protocol
  description: |
    Flask Extension for the MQTT protocol. Basically it is a thin wrapper
    around paho-mqtt and aimes to simplify MQTT integration in Flask.
    MQTT is a machine-to-machine "Internet of Things" protocol and was
    designed for extremely lightweight publish/subscribe messaging transport.
  doc_url: https://flask-mqtt.readthedocs.io
  dev_url: https://github.com/stlehmann/Flask-MQTT

extra:
  recipe-maintainers:
    - stlehmann
