{% set name = "flask-mqtt" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stlehmann/Flask-MQTT/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e4e51cbbc848de52c18261aaadc696331da4110500ac2e62794d12a9ce2fa6c9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - flask
    - paho-mqtt

test:
  requires:
    - python {{ python_min }}
  imports:
    - flask_mqtt

about:
  home: https://github.com/stlehmann/Flask-MQTT
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple, Flask Extension for the MQTT protocol
  description: |
    Flask Extension for the MQTT protocol. Basically it is a thin wrapper
    around paho-mqtt and aimes to simplify MQTT integration in Flask.
    MQTT is a machine-to-machine "Internet of Things" protocol and was
    designed for extremely lightweight publish/subscribe messaging transport.
  doc_url: https://flask-mqtt.readthedocs.io
  dev_url: https://github.com/stlehmann/Flask-MQTT

extra:
  recipe-maintainers:
    - stlehmann
